name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 AM IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### content
          SHOW_TITLE: true 
          SECTION_NAME: waka
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          LANG_COUNT: 7
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          STOP_AT_OTHER: true 
